"""empty message

Revision ID: f795306d9f6a
Revises: 18408c6b5e47
Create Date: 2023-04-04 12:36:04.374503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f795306d9f6a'
down_revision = '18408c6b5e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_people', schema=None) as batch_op:
        batch_op.alter_column('favorite_people_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_people', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('favorite_people_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
